Fix compatibility with RSpec 2.x
::RSpec.configuration.start_time= was added in RSpec 3.0.0.

This method doesn't exist in RSpec 2.x, so the binstub fails with  `spring-commands-rspec-1.0.3/lib/spring/commands/rspec.rb:17:in `call': undefined method `start_time=' for #<RSpec::Core::Configuration:0x007f6d388dcf00> (NoMethodError)`

Check if the start_time= method exists before calling it.